# Generated by Django 3.1.6 on 2021-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jandis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendance',
            field=models.CharField(blank=True, choices=[('0', 'absent'), ('1', 'attendance')], max_length=30, null=True, verbose_name='is_attendance'),
        ),
    ]
